### PR TITLE
add mkdocs based on the readme.md.

### PR DESCRIPTION
**Pull request by maraflush**
Hello @hypn0s ,

I filled out your docs markdown files with the readme information.

Regards,

### CODE REVIEW

**Comment by hypn0s** [comment]
Hi @maraflush ,

Thank you for your PR. I would suggest to remove your .gitignore file.

Also, the documentation does not look good when I build it as multiline code blocks are rendered in only a 1 line. Can you check if you have the same issue and fix it?

**Comment by maraflush** [comment]
My screen :
docs

**Comment by maraflush** [comment]
BTW : The credits screen do not contains the code of the previous page. It's an error of mine not the generated by medics

**Comment by maraflush** [comment]
Hello @hypn0s ,

The following images roll shows you the generated docs in my side :

docs

Regards,

**Comment by maraflush** [comment]
Only the big bash command **Authentication brute** is trimmed.

**Comment by hypn0s** [comment]
Thank you @maraflush for this PR!

**Pull request merged**
