### PR TITLE
Add undeploy function and code refactoring

### PR DESCRIPTION
**Pull request by kalidor**
Hi, I discovered your tools during a pentest, very useful :)
I add undeploy function and a function to list installed app.
Also i did some code refactoring.

### CODE REVIEW

**Comment by hypn0s** [comment]
Hello, thank you for your patch! I'm glad you found this repo :)

I think there is something wrong with your indentation at lines 260 and 286. Please fix this and I'll test and merge your PR :)

**Comment by kalidor** [comment]
Ok, I fixed it and test it. Should work for you too

**Comment by hypn0s** [comment]
Hi!

Sorry for the wait!

I just tested your code, but I got an "Upload failed" now when I upload a simple WAR file. This is due to your test to know if the app was correctly deployed.
I propose you to add the following patch to your code before I accept the PR, just to make sure I merge working code :) :
```diff
@@ -197,6 +197,7 @@ class Tomcat(object):
                attributes = [{"name": "req_attribute", "value": ("JK_LB_ACTIVATION", "ACT")}, {"name": "req_attribute", "value": ("AJP_REMOTE_PORT", "12345")}]
                if old_version == False:
                        attributes.append({"name": "query_string", "value": deploy_csrf_token})
+               old_apps = self.list_installed_applications(user, password, old_version)
                r = self.perform_request("/manager/html/upload", headers=headers, method="POST", user=user, password=password, attributes=attributes)
 
                with open("/tmp/request", "rb") as f:
@@ -210,9 +211,8 @@ class Tomcat(object):
                while r.prefix_code != AjpResponse.END_RESPONSE:
                        r = AjpResponse.receive(self.stream)
                logger.debug('Upload seems normal. Checking...')
-               # since Tomcat only respond "OK", we are not sure if application is well deployed
-               # How to know the path of installed application (make a diff) ?
-               if '/jsp_app' in self.list_installed_applications(user, password, old_version):
+               new_apps = self.list_installed_applications(user, password, old_version)
+               if len(new_apps) == len(old_apps) + 1 and new_apps[:-1] == old_apps:  
                        logger.info('Upload success!')
                else:
                        logger.error('Upload failed')
```

Otherwise, great additions! Love the list command :)

**Comment by hypn0s** [comment]
Nevermind, I just commited myself the fix. Thank you for your help!

**Pull request merged**
